name: Build only

on:
  workflow_dispatch:
  pull_request:
  # push:
  #   branches:
  #     - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0 # 18
      - name: Install Dependencies
        run: npm i # was npm ci
      - name: Build Quartz
        run: npx quartz build
