name: Quartz - Deploy to GitHub Pages (pnpm)

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 18

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm i
      - name: Build Quartz Site
        run: npx quartz build
      - uses: actions/upload-pages-artifact@v3
        name: Upload artifact
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
